N <- 200
b1 <- 0.5 
b2 <- 0.75 
b3 <- 0.5 
b4 <- 1.2
b5 <- 0.5
b6 <- -1.5 
b7 <- 0.4 
se1 <- 0.5 
se2 <- 1.5 
se3 <- 1.5

set.seed(123) 
E1 <- rnorm(N) 
E2 <- rnorm(N) 
M1 <- E1*b2 + rnorm(N,sd = se1) 
M2 <- E1*b4+E2*b5+ rnorm(N,sd = se2) 
W <- E1*b1+M1*b3+M2*b7+ rnorm(N,sd = se3)

# linear models reprenseting the DAG
m.m1 <- lm(M1 ~ E1)
m.m2 <- lm(M2 ~ E1 + E2)
m.w <- lm(W ~ E1 + M1 + M2)

# make data.frame for predictions. 
mydata <- data.frame(E1,mean(E2),M1=mean(M1),M2=mean(M2))

# direct effect to w ++++++++++++++ 
eff.dir <- predict(m.w,newdata = mydata) 

# effect thought M1 ++++++++++++++++ 
mydata$M1 <- predict(m.m1,newdata = mydata)
# block direct path by fixing at average 
mydata$E1 <- mean(E1) 
eff.m1 <- predict(m.w,newdata = mydata) 

# effect through M2 +++++++++++++++
mydata$M2 <- predict(m.m2,newdata = mydata) 
# block direct path by fixing at average 
mydata$E1 <- mean(E1)
eff.m2 <- predict(m.w,newdata = mydata)

# full effect ++++++++++++++++++ 
mydata$E1 <- E1
mydata$M1 <- predict(m.m1,newdata = mydata) 
mydata$M2 <- predict(m.m2,newdata = mydata) 
eff.full <- predict(m.w,newdata = mydata) 


var.par <- data.frame(var(eff.dir), 
                      var(eff.m1), 
                      var(eff.m2))
var.par <- var.par/rowSums(var.par)*100 
knitr::kable(var.par)

#slope of generated by each path
slopes= data.frame(eff.dir=coef(lm(eff.dir~E1))[2],
                   eff.m1=coef(lm(eff.m1~E1))[2],
                   eff.m2=coef(lm(eff.m2~E1))[2],
                   eff.full=coef(lm(eff.full~E1))[2] ) 
knitr::kable(slopes)

###################################################################

# Example with our data

# linear models reprenseting the DAG
mod_FFD <- lmer(FFD_s~mean_3+(1|id),data=data_selag)
mod_graz<-glmer(cbind(grazing_success,grazing_failure)~mean_3+FFD_s+(1|id),data=data_selag,family="binomial")

# make data.frame for predictions. 
mydata <- with(subset(data_selag,!is.na(grazing_success)&!is.na(FFD_s)),data.frame(mean_3,FFD_s=mean(FFD_s,na.rm=T),id))

# direct effect to grazing ++++++++++++++ 
eff.dir <- predict(mod_graz,newdata = mydata) 

# effect thought FFD ++++++++++++++++ 
mydata$FFD_s <- predict(mod_FFD,newdata = mydata)
# block direct path by fixing at average 
mydata$mean_3 <- mean(subset(data_selag,!is.na(grazing_success)&!is.na(FFD_s))$mean_3) 
eff.FFD <- predict(mod_graz,newdata = mydata) 

# full effect ++++++++++++++++++ 
mydata$mean_3 <- subset(data_selag,!is.na(grazing_success)&!is.na(FFD_s))$mean_3
mydata$FFD_s <- predict(mod_FFD,newdata = mydata) 
eff.full <- predict(mod_graz,newdata = mydata) 

var.par <- data.frame(var(eff.dir), 
                      var(eff.FFD))
var.par <- var.par/rowSums(var.par)*100 
knitr::kable(var.par)

#| var.eff.dir.| var.eff.FFD.|
#|------------:|------------:|
#|     50.96837|     49.03163|

#slope of generated by each path
slopes= data.frame(eff.dir=coef(lm(eff.dir~subset(data_selag,!is.na(grazing_success)&!is.na(FFD_s))$mean_3))[2],
                   eff.FFD=coef(lm(eff.FFD~subset(data_selag,!is.na(grazing_success)&!is.na(FFD_s))$mean_3))[2],
                   eff.full=coef(lm(eff.full~subset(data_selag,!is.na(grazing_success)&!is.na(FFD_s))$mean_3))[2] ) 
knitr::kable(slopes)



